GTNewHorizons/BetterQuesting

src/main/java/betterquesting/api/client/gui/lists/GuiScrollingFluids.java, src/main/java/betterquesting/api/client/gui/lists/GuiScrollingItems.java
https://github.com/Funwayguy/BetterQuesting/issues/270
=> Re-add support for NEI

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/api2/client/gui/panels/bars/PanelHScrollBar.java, src/main/java/betterquesting/api2/client/gui/panels/bars/PanelVScrollBar.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasScrolling.java, src/main/java/betterquesting/handlers/ConfigHandler.java
It always infuriated that I couldn’t quickly move from the beginning to the end of the list of quest lines using the mouse wheel, so i implemented that.
=> Add ability to change scrolling speed

src/main/java/betterquesting/api2/client/gui/panels/CanvasMinimum.java, src/main/java/betterquesting/client/gui2/GuiQuest.java
Removes pages for rewards and tasks, now they are all displayed in a scrolling list.
Demo: https://youtu.be/VQiZk7f15EY
***REQUIRES: https://github.com/GTNewHorizons/StandardQuestingPack/pull/4***
=> Remove paginating

src/main/java/betterquesting/commands/BQ_CopyProgress.java, src/main/java/betterquesting/core/BetterQuesting.java
`/bq_copyquests [toPlayer] <fromPlayer>`
=> Add command to copy quest progress

src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasScrolling.java, src/main/java/betterquesting/client/gui2/editors/designer/GuiDesigner.java, src/main/java/betterquesting/client/gui2/editors/designer/PanelToolController.java, src/main/java/betterquesting/client/toolbox/PanelTabMain.java
This improves the designer so that it fits the current questline to the view on open (like the gameplay questline view does), and adds a tool button to fit to view as well.
=> Improve designer support

src/main/java/betterquesting/api/questing/IQuest.java, src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java, src/main/java/betterquesting/questing/QuestInstance.java
Problem
> for some reason a quest becomes repeatable with value -1 after I finish it
solved.
=> Quest state fix

src/main/java/betterquesting/client/gui2/GuiQuestLines.java
*Sorry for the question marks in the screenshot. Tested on vanilla with quests from GTNH*
=> Fix checkmarks on questlines

src/main/java/betterquesting/api2/client/gui/controls/PanelButtonCustom.java, src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestSearch.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/client/gui2/GuiQuestSearch.java, src/main/java/betterquesting/misc/QuestSearchEntry.java
Implementation of [this feature request](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6699)
https://user-images.githubusercontent.com/29896317/103277685-a4b5ad00-49da-11eb-9bae-635f96a670db.mp4
=> Quest search

src/main/java/betterquesting/network/handlers/NetQuestEdit.java
GTNewHorizons/GT-New-Horizons-Modpack#7748
=> Added logging of quest completion

src/main/java/betterquesting/commands/BQ_CommandAdmin.java, src/main/java/betterquesting/commands/admin/QuestCommandCheckCompletion.java, src/main/java/betterquesting/commands/admin/QuestCommandReportAllProgress.java, src/main/resources/assets/betterquesting/lang/en_US.lang
GTNewHorizons/GT-New-Horizons-Modpack#7747
=> Add admin commands to check quest progress of a given player

src/main/java/betterquesting/client/gui2/GuiQuestSearch.java
GTNewHorizons/GT-New-Horizons-Modpack#7951
=> Lock focus to text box in search gui

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/api2/cache/QuestCache.java, src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java, src/main/java/betterquesting/api2/client/gui/themes/presets/PresetIcon.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/resources/assets/betterquesting/lang/en_US.lang, src/main/resources/assets/betterquesting/lang/zh_CN.lang
=> Add view mode button

src/main/java/betterquesting/api/utils/JsonHelper.java
https://discord.com/channels/181078474394566657/181078474394566657/920651574441832488
=> Pretty print all jsons

src/main/java/betterquesting/api/questing/IQuest.java, src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestLine.java, src/main/java/betterquesting/api2/client/gui/themes/presets/PresetColor.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/client/gui2/editors/GuiPrerequisiteEditor.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/resources/assets/betterquesting/lang/en_US.lang
Better than #48, also conflict with that.
=> Improve implicit dependency handling

src/main/java/betterquesting/commands/BQ_CommandAdmin.java, src/main/java/betterquesting/commands/admin/QuestCommandCleanupQuestLine.java, src/main/java/betterquesting/questing/QuestLineEntry.java, src/main/resources/assets/betterquesting/lang/en_US.lang
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9310
=> Add command to cleanup invalid entries from questline

src/main/java/betterquesting/client/gui2/GuiQuest.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8766
=> Fix task panels not initializing on large scroll offset

src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestSearch.java
close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9624
=> Searching "@complete" in the questbook gives a list of completed quests with rewards unclaimed

src/main/java/betterquesting/api/events/MarkDirtyPlayerEvent.java, src/main/java/betterquesting/api2/storage/INBTProgress.java, src/main/java/betterquesting/api2/utils/DirtyPlayerMarker.java, src/main/java/betterquesting/handlers/EventHandler.java, src/main/java/betterquesting/handlers/SaveLoadHandler.java, src/main/java/betterquesting/network/handlers/NetQuestEdit.java, src/main/java/betterquesting/questing/QuestInstance.java, src/main/java/betterquesting/questing/tasks/TaskStorage.java
Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9662
Tested in SP only, seems to work properly
Not tested in server yet
Feedback welcome
=> Store progress for per player individually

src/main/java/betterquesting/api/questing/tasks/ITask.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestSearch.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasSearch.java
- Allow searching quest description
- Allow searching task-specific texts (like item name)
- actual implementation is in another PR
=> Allow searching more texts

build.gradle, src/main/java/betterquesting/api/utils/ItemComparison.java
Do NBT comparisons last when matching ItemStacks to reduce lag, this should allow for a very quick rejection path for items with different IDs
=> Optimize ItemComparison

src/main/java/betterquesting/blocks/TileSubmitStation.java
| Before                                                       | After                                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| <video src="https://user-images.githubusercontent.com/49554020/171100594-2d902a5c-0018-41a2-af5a-e80663fd8aaa.mp4"> | <video src="https://user-images.githubusercontent.com/49554020/171100615-c06c3207-c166-42fd-8c06-b54e41a6dffe.mp4"> |
=> Fix OSS voiding items when submitting fluid tasks

src/main/java/betterquesting/commands/admin/QuestCommandReset.java
Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10639>
=> Fix the reset command not persisting changes

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/handlers/ConfigHandler.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11443
=> Add a config option to see locked UNLOCKED visibility quest line in view mode

src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/client/toolbox/tools/ToolboxToolReset.java, src/main/java/betterquesting/commands/BQ_CommandClient.java, src/main/java/betterquesting/commands/client/QuestCommandShow.java, src/main/java/betterquesting/core/proxies/ClientProxy.java, src/main/java/betterquesting/handlers/EventHandler.java, src/main/resources/assets/betterquesting/lang/en_US.lang
Most notable feature is the share quest via chat. this looks really nice and would solve a lot of headache I'm having right now.
=> Cherry pick more changes from 1.12 fork

src/main/java/betterquesting/handlers/EventHandler.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10294
=> reset completion info for quest progress update from server

build.gradle, src/main/java/betterquesting/api/enums/EnumLogic.java, src/main/java/betterquesting/api/questing/IQuest.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/questing/QuestInstance.java
Previously we deduct total quests if we detect an XOR quest, however it's a nontrivial task to figure out how many quest can be completed if quest logic is XOR, and sometimes it's not even a constant. Given we generally want the displayed total quest to stay the same, I decided to count uncompleteable quest as completed as well. 
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11556
=> change how quests with exotic quest logic are counted towards completion

build.gradle, src/main/java/betterquesting/api2/utils/OreIngredient.java
This pretty much explains why it didn't happen on dev env and sometimes stacksizes were random
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11781
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12058
=> Fix OreIngredient leaking raw oredictionary entries

addon.gradle, src/main/java/betterquesting/api2/cache/QuestCache.java, src/main/java/betterquesting/api2/utils/QuestTranslation.java, src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java
Fixes a few bugs in the new UUID stuff
=> Fix new db

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java, src/main/java/betterquesting/handlers/ConfigHandler.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13050
=> fix clickable url hotzone detection not ignoring linebreaks in raw text

dependencies.gradle, src/main/java/betterquesting/api/utils/UuidConverter.java, src/main/java/betterquesting/api2/utils/QuestTranslation.java, src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java, src/main/java/betterquesting/core/BetterQuesting.java, src/main/java/betterquesting/handlers/SaveLoadHandler.java
Save quest line order in a separate text file, to reduce merge conflicts.
Pre-built jars:
* [libs.zip](https://github.com/GTNewHorizons/BetterQuesting/files/11128780/libs.zip)
Quest format will be updated in:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13081
=> Split out quest line order

src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13050
=> fix url hotzone misalignment when format specifier are used

src/main/java/bq_standard/client/gui/tasks/PanelTaskHunt.java
Wisp preview before:
Wisp preview now:
=> Adapted Wisp entity preview.

dependencies.gradle, src/main/java/betterquesting/api/utils/RenderUtils.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelEntityPreview.java
The Hydra model little bit better.
Also [14085](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14085) can be closed with this.
=> Added heads to the Hydra and body to the Naga.

build.gradle, dependencies.gradle, src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java, src/main/java/betterquesting/client/gui2/GuiHome.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/bq_standard/integration/nei/QuestRecipeHandler.java
Close https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/104
=> Show previously shown screen when closed

src/main/java/betterquesting/client/QuestNotification.java, src/main/java/betterquesting/handlers/EventHandler.java
- Now draw string with Shadow
- Stop drawing the item stack when the alpha drops below a certain level because we can't make it fade away like the text
=> Small changes for quest HUD text render

src/main/java/betterquesting/api/utils/JsonHelper.java
Also ditches the endless duping of malformed files and overwrites instead.
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14806
=> Ignore .DS_Store and old "malformed" files

src/main/java/betterquesting/client/QuestNotification.java
Stop setting GL states to the state they are already in
Fix for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15039
=> Fix quest notif hud rendering issue

src/main/java/betterquesting/client/gui2/editors/nbt/GuiNbtAdd.java
fix https://discord.com/channels/181078474394566657/949447391587733504/1187061901843251221
=> fix inserting into empty tag list not setting tag type

src/main/java/bq_standard/rewards/RewardQuestCompletion.java
now to see reward changes u need to relogin on server
=> cache update in RewardQuestCompletion

dependencies.gradle, src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/commands/BQ_CommandAdmin.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/java/betterquesting/questing/QuestDatabase.java, src/main/java/betterquesting/questing/QuestLineDatabase.java
Might help shine some light on how/why https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16861, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16861 & https://discord.com/channels/181078474394566657/522098956491030558/1278320296289632318 happens.
=> Better logging when encountering null quests

src/main/java/betterquesting/api2/client/gui/controls/PanelTextField.java
There's absolutely no reason for this to be commented out
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18681
=> Don't go back to previous screen when r-clicking searchbar

src/main/java/betterquesting/handlers/EventHandler.java
Related issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19336
Tested in game, functioning as intended, please check for possible problems.
=> Localized quest names on pop-ups

src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java, src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java, src/main/java/betterquesting/client/gui2/editors/GuiRewardEditor.java, src/main/java/betterquesting/client/gui2/editors/GuiTaskEditor.java, src/main/java/betterquesting/network/handlers/NetChapterEdit.java, src/main/java/betterquesting/network/handlers/NetImport.java, src/main/java/betterquesting/network/handlers/NetQuestEdit.java, src/main/java/bq_standard/network/handlers/NetLootImport.java, src/main/java/bq_standard/network/handlers/NetLootSync.java
both do essentially the same thing, but the former is only available with realms.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20535
=> Replace com.mojang.realmsclient.gui.ChatFormatting with EnumChatFormatting

dependencies.gradle, src/main/java/betterquesting/api/utils/RenderUtils.java, src/main/java/betterquesting/core/BetterQuesting.java, src/main/java/betterquesting/core/proxies/ClientProxy.java
Depends on https://github.com/GTNewHorizons/GTNHLib/pull/169 and https://github.com/GTNewHorizons/Angelica/pull/1017
Fixes issues when used with the custom font PR.
=> Use GTNHLib string methods

dependencies.gradle, src/main/java/betterquesting/api2/cache/QuestCache.java, src/main/java/betterquesting/client/gui2/GuiQuest.java, src/main/java/betterquesting/commands/BQ_CommandAdmin.java, src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java, src/main/java/betterquesting/core/BetterQuesting.java, src/main/java/bq_standard/integration/vendingmachine/VmAdapter.java, src/main/resources/assets/bq_standard/lang/en_US.lang
Requires Vending Machine build 0.4.0.
Steps:
1. Publish VM 0.4.0 to maven repo https://nexus.gtnewhorizons.com/#browse/browse:releases:com%2Fcubefury%2Fvendingmachine%2FVendingMachine
2. Add VM to GT5U modlist https://github.com/GTNewHorizons/GT5-Unofficial/pull/5009
3. **Update BetterQuesting with VM integration (This PR)**
4. Add Default Trade list to config in main modpack repo https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/21829
5. Update Coremod with recipes https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1398
=> Vending integration
