src/main/java/betterquesting/handlers/EventHandler.java
Now, when one player completes the task, it is immediately updated for everyone in group
=> Fix party quest completion sync

src/main/java/betterquesting/api/enums/EnumQuestState.java, src/main/java/betterquesting/api/questing/IQuest.java, src/main/java/betterquesting/api2/cache/QuestCache.java, src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestLine.java, src/main/java/betterquesting/api2/client/gui/themes/presets/PresetColor.java, src/main/java/betterquesting/api2/client/gui/themes/presets/PresetTexture.java, src/main/java/betterquesting/client/gui2/GuiThemes.java, src/main/java/betterquesting/client/themes/ThemeLegacy.java, src/main/java/betterquesting/questing/QuestInstance.java, src/main/resources/assets/betterquesting/bq_themes.json, src/main/resources/assets/betterquesting/lang/en_US.lang, src/main/resources/assets/betterquesting/lang/ru_RU.lang, src/main/resources/assets/betterquesting/lang/zh_CN.lang, src/main/resources/bq_themes.json
* Possible fix for non-resetting repeatable quests
* Add warning about `edit mode` enabled to repeatable quests tooltip
* Fix negative time display in tooltip
* Replaced pending rewards in tooltip when quest can be repeated
* Add new visual for quest what can be repeated INSTEAD of marking them as quests with non-claimed reward
=> Repeatable quests improvements

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/handlers/ConfigHandler.java
[Suggestion in discord:](https://discord.com/channels/181078474394566657/181078474394566657/794253459913572352)
> `several people is typing` 31.12.2020
> @ShadowKillerPro can it be somehow configured so that betterquesting would not hide the sidebar by default every time a client is started? Not that its all that annoying but in fact it is annoying that it always starts in auto-hide mode
=> Add saving lock tray state

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/client/gui2/GuiHome.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/java/betterquesting/handlers/EventHandler.java
[Suggestion from discord](https://discord.com/channels/181078474394566657/289850721988509696/794266130532925450):
> @ShadowKillerPro Я предлагаю вернуть стартовую страницу со вкладками в квестах как было раньше. Раздражает необходимость каждый раз её открывать.
or, in English (close to text):
> I suggest return the quest lines gui as start page as it was before. It is annoying to have to open it every time.
-------------
Now mod will open `home gui` only if we close BQ's gui at `home gui`, otherwise start page - `questlines gui`. However, we can always return to `home gui` from the `questline gui` with "back" button
=> Allow skip home and open quests gui at start

src/main/java/betterquesting/api2/storage/EmptyLookupLogic.java, src/main/java/betterquesting/api2/storage/LookupLogicType.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7599
```
java.util.NoSuchElementException
at java.util.TreeMap.key(Unknown Source)
at java.util.TreeMap.lastKey(Unknown Source)
at betterquesting.api2.storage.LookupLogicType.lambda$static$0(LookupLogicType.java:10)
at betterquesting.api2.storage.LookupLogicType.determine(LookupLogicType.java:26)
at betterquesting.api2.storage.SimpleDatabase.updateLookupLogic(SimpleDatabase.java:44)
```
did not test, but should work?
=> fix no such element on empty database

src/main/java/betterquesting/api/utils/JsonHelper.java, src/main/java/betterquesting/handlers/SaveLoadHandler.java
This happens with high probability with FTBU backup.
https://discord.com/channels/181078474394566657/234936569360809996/832819747028074517
BQ3 use asynchronous IO to save its database. In this process there will be a few temporary files created then removed. If ftbu happens to be running backup while this is happening, there is a good chance of race condition, and hence stopping ftbu from properlly making a backup. This PR ensures BQ3 returns only if all the file IO has finished.
=> Wait for IO finish upon save

src/main/java/betterquesting/api2/storage/NaiveLookupLogic.java
This will address Prometheus's problem of quest not appearing in questline after being added via designer.
=> Fix NaiveLookupLogic not invalidating ref cache upon changes to the underlying map

src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasItemDatabase.java
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8076
Probably an item stack with a null item. I don't quite know who is null, but this should prevent all crashes like this.
=> Guard against broken mods returning invalid itemstack

src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestLine.java
Fixes this
https://user-images.githubusercontent.com/40035906/162563865-99bb6fc4-481c-4029-aa61-74dc193135f2.mp4
In the video, dependency toward chemical bath is normal, the other is implicit. The former should not blink.
=> Fix mixing normal and implicit requirements draws lines incorrectly

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java, src/main/java/betterquesting/handlers/ConfigHandler.java
Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10354
BQ + smooth-font
Some text is blocked
---
So add a config to correct the width of the split text:
---
Effect
=> Add a config to correct the width of the split text

src/main/java/betterquesting/client/gui2/GuiQuest.java
Fixes GTNewHorizons/GT-New-Horizons-Modpack#10617 which I has also noticed playing around in the editor.
I'm not sure this is the right fix as it only avoids the consequences of the NPE, and I'm not sure whether that situation is supposed to be possible or not.
=> Don't crash if a taskGui or rewardGui isn't available

src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java
Fixes the Backspace action introduced in #72 by ensuring that the previous screen change does not happen when the backspace key actually performs an action on the current panel.
There were changes to the backspace action introduced in the Cleanroom fork later on that fixed the backspace action, but where missed in that PR.
=> Fix backspace going back while typing

build.gradle, dependencies.gradle, src/main/java/betterquesting/handlers/SaveLoadHandler.java, src/main/java/betterquesting/questing/QuestInstance.java
#61 left the original merged progress file in place and kept loading from it, even though the only updates were written to the new files. Instead here I mark all data as dirty on first load of the old format, and move the old data file to a backup location on first save after that to prevent it from being read again.
=> More quest resetting fixes

src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java, src/main/java/betterquesting/client/gui2/GuiQuest.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7926
The URL is not detected automatically for clarity (but can be made to, with some minor code edit). You have to wrap the link between `[url]....[/url]`. When rendering, only stuff within the bracket will be visible. There is no implicit style change, e.g. add underline and make it blue. If you want it, you will have to do it yourself via traditional minecraft formatting codes.
While the infrasturcture is there, such "url awareness" is only enabled for quest description in quest gui. if needed, it can be easily enabled for most other places where a text is displayed.
=> add clickable URI to quest description

src/main/java/betterquesting/api/questing/IQuestLineDatabase.java, src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java, src/main/java/betterquesting/questing/QuestLineDatabase.java
Split up quest lines into separate files, similar to what was done for quests. Hopefully the last format change for a while.
Note: this change is incompatible with dev quest book formats, which will still look for the `QuestLines.json` file that no longer exists. This shouldn't be a problem for anyone else, since I will update the quest book format data once this PR, and all quest book data PRs, are merged, but in case it is, you can update the format with the following steps:
1. Use old BetterQuesting version, prior to this PR
2. Copy over the latest quest book data (in old format) from HEAD into `.minecraft/config/betterquesting/DefaultQuests/`
3. `/bq_admin default load`
4. `/bq_admin default savelegacy`
5. Delete `.minecraft/config/betterquesting/DefaultQuests/` directory
6. Switch to …
=> Split up quest lines into separate files

src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java
This check will catch left over quest line files, and prevent silently clobbering quest line data.
=> Add check for duplicate quest line order

src/main/java/bq_standard/client/gui/panels/content/PanelItemSlotBuilder.java
on my custom servers, I prefer to update log4j to the latest versions instead of various patches
in new versions this function has changed its location, which leads to incompatibility, and in general I don’t understand why to use asserts from there
=> fix compatibility for new log4j versions

src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java
* Fix printing quests multiple times in `en_US.lang`
* Apply limit to length of file names
Fixes:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13071
(if it doesn't, there's a few more things we can do to further reduce file name length, if we have to)
=> Some small fixes for BQ format

src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java
As requested in:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13172
=> Remove quest IDs from tooltips

dependencies.gradle
* Updated NotEnoughItems:2.3.27 to 2.3.40
* Builds are failing since there's an outdated dependency
=> Update build dependencies

src/main/java/betterquesting/api2/client/gui/panels/content/PanelEntityPreview.java, src/main/java/bq_standard/client/gui/tasks/PanelTaskHunt.java
Trying to resolve this [#14085](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14085) problem I have realized that this [PanelTaskHunt.java#L52](https://github.com/GTNewHorizons/BetterQuesting/blob/master/src/main/java/bq_standard/client/gui/tasks/PanelTaskHunt.java#L52) code should also be at [PanelTaskMeeting.java#L49](https://github.com/GTNewHorizons/BetterQuesting/blob/master/src/main/java/bq_standard/client/gui/tasks/PanelTaskMeeting.java#L49) and [PanelTaskInteractEntity.java#L81](https://github.com/GTNewHorizons/BetterQuesting/blob/master/src/main/java/bq_standard/client/gui/tasks/PanelTaskInteractEntity.java#L81), so by respecting DRY principle I have moved it to [PanelEntityPreview.java#L109](https://github.com/FindMeSomeFun/BetterQuesting/blob/master/src/main/jav …
=> Adapted Wisp entity preview but by respecting DRY principle this time.

src/main/java/betterquesting/api/utils/RenderUtils.java, src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelEntityPreview.java
I tried to export quests with NESQL Exporter in 2.3.6 just to check if everything was ok and the Wisp's model was empty. Then I checked the questbook, and it was missing there too. So after some WTF moments and some digging around, I realized that the Wisp's model rendering respects the player's pitch. You can confirm this in earlier versions by looking at the Wisp's model with a different vertical angle.
When I made the last two changes, I used a map that I use for NESQL Exporter where the player always looks at its feet.
To get Wisp's model preview to rotate around the Y axis, it needs to be positioned horizontally (pitch 90 degrees), but its preview also depends on the player's pitch, so it also needs to be 90 degrees. So for a preview to be fully visible like it is in the game, the …
=> Wisp final solution

src/main/java/betterquesting/client/QuestNotification.java
Partial revert of: https://github.com/GTNewHorizons/BetterQuesting/pull/124
Reported 7 years ago here: https://github.com/Funwayguy/BetterQuesting/issues/75
Fixed by original maintainer here: https://github.com/Funwayguy/BetterQuesting/commit/9cda540a5e7779f6561c44a734fd3006cde63eea
Not blending causes black screen and disabling blend at the end causes black screen... I don't get it but I can no longer reproduce.
Also makes the notification text disappear at the same time as the icon.
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15193
=> Fix quest completion notification causing black screen

src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/commands/BQ_CommandAdmin.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/java/drethic/questbook/config/QBConfig.java
Adds a new config option `unrestrictAdminCommands` which allows everyone to use `/bq_admin` commands when set to true without checking for permission.  
Which can be useful for single-player so you don't have to do the "_Open to LAN, enable cheats, use command, exit world, re-join world_" trick.
Uses an `@Override canCommandSenderUseCommand` similarly to how the class `BQ_CommandUser` does.
Using the ConfigHandler both client and server are handshaking nicely.
=> unrestrictAdminCommands Config Option

src/main/java/betterquesting/api2/utils/QuestTranslation.java, src/main/java/bq_standard/integration/nei/QuestRecipeHandler.java, src/main/resources/assets/bq_standard/lang/en_US.lang
This PR adds the following:
- Text color customization for the quest names displayed in NEI by providing a hex color in bq_standard's `.lang` file.
- Make the debug stopwatch start only if the debug flag is set to `true`
This is deliberately not part of a theme, since it should provide a way to make text readable on custom gui textures for resource pack creators. Themes are placed in `config/betterquesting/resources` and thus are not changeable by a resource pack.
=> NEI text color customization with lang file

src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java, src/main/java/betterquesting/client/gui2/editors/GuiTextEditor.java, src/main/resources/assets/betterquesting/bq_themes.json
This PR adds new options in the text formatting of quest descriptions. Instead of using the previously added buttons to [format text with color and some extra options, as done by vanilla Minecraft text formatting rules](https://minecraft.fandom.com/wiki/Formatting_codes), these new buttons add a block of text with specific formatting, so that devs can follow a standard of formatting. [In the developer's guide for making quests](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/config/betterquesting), there are only three colors mentioned, all of which are included here: dark red for warnings, dark aqua for "PS:" entries and default for the rest of the text. On top of that, hyperlinks are supposed to be underlined and colored dark-blue, although I set the color here to …
=> Add Formatting Macros for Quest Descriptions

src/main/java/betterquesting/api2/client/gui/misc/TextureSizeHelper.java, src/main/java/betterquesting/api2/client/gui/misc/URIHandlers.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java, src/main/java/betterquesting/api2/client/gui/resources/textures/SimpleNoUVTexture.java, src/main/java/betterquesting/client/gui2/GuiQuest.java
* image transforms
* responsive layout/image sizing beyond what I currently implemented
* custom quest background
* render image inline like emojis
* clickable image (as in click to zoom)
* image as hyperlink
current syntax is simple: `[img height=<height_in_pixels>] <resource_location>[/img]`
`height_in_pixels`: the suggested height of image. width of the image will be auto determined based on actual height and aspect ratio of image drawn. note the actual height might be smaller than this if resizing will leave some blank on vertical axis.
`resource_location`: stuff like `quest:example.png`. if you don't quite understand how resource packs works, a simple way of utilizing this feature is to put your images into `config/betterquesting/resources/gtnhquests/`. In that case, if the image to …
=> embed images

dependencies.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle, src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasQuestLine.java, src/main/java/betterquesting/client/gui2/GuiQuestLines.java, src/main/java/betterquesting/core/BetterQuesting.java
When searching for a quest it will now zoom in fully and center the screen on the quest.
In case that doesn't make the quest obvious enough I also changed it to more clearly flash yellow instead of the very slight color change it had before.
The flashing felt too slow so I made it a bit faster:
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14757
=> Make searched quests more noticeable

src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java, src/main/java/betterquesting/api2/client/gui/popups/PopWaitExternalEvent.java, src/main/java/betterquesting/client/gui2/editors/GuiQuestEditor.java, src/main/java/betterquesting/client/gui2/editors/GuiTextEditor.java, src/main/java/betterquesting/misc/QuestResourcesFile.java, src/main/java/betterquesting/misc/QuestResourcesFolder.java, src/main/resources/assets/betterquesting/lang/en_US.lang
Adds 2 buttons to quest description editor.
1. Select image
* If editor selected a file under config/betterquesting/resources/, then it will be used. A proper mage tag WITHOUT height specified pointing towards that image will be written into the main textbox.
* if editor selected a file outside aforementioned directory, then editor will be prompted to select a location under that directory. The image will be then copied to that selected location. Afterwards, a proper mage tag WITHOUT height specified pointing towards that image will be written into the main textbox. 
In either case, only PNG is allowed to be selected.
2. Image. This button is pretty much the same as any other style tag button. Just wraps whatever that is already under your cursor in a pair of `[img][/img]` tag, with a …
=> add gui to select image on local disk

src/main/java/betterquesting/api/questing/IQuestLine.java, src/main/java/betterquesting/api2/storage/UuidDatabase.java, src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java, src/main/java/betterquesting/questing/QuestLine.java
Update quest line format in saved quest data, to use separate files per entry. The current format stores all entries as a list within a single file, which has caused problems with merges in the past. As requested / discussed here:
*   https://discord.com/channels/181078474394566657/949447391587733504/1216196017742020732
The new format is, instead of a file per quest line under `QuestLines/`, we have a subdirectory for each quest line. Each subdirectory contains a file named `QuestLine.json`, which contains all of the quest line information other than quest line entries. Each quest line entry is now stored as a separate file in the subdirectory, named after the quest that the entry is for.
I also updated the sort order for UUID databases to use string comparison on the encoded strings, …
=> Quest line save format

src/main/java/betterquesting/commands/admin/QuestCommandDefaults.java
It was failing when the output directory already existed
=> Fix `exportlang` command

src/main/java/betterquesting/api2/client/gui/panels/content/FormattingTag.java, src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java
Implement nested formatting tags, and also add tags for text formatting: bold, italic, underline, strikethrough, obfuscated.
This lets us do things like:
```
[warning]Do [bold]NOT[/bold] build machines in the §9rain§r![/warning]
```
and have it all work as expected.
---
This PR also changes the semantics of the `[url]` tag: instead of being able to specify alternate anchor text for the URL using a `text=` param, now the link itself can be specified using a `link=` param, in which case the text inside the `[url]` tag is used as the anchor text. This change allows applying formatting to the anchor text. I searched the quest database, and didn't find any current usages of the `text=` param, so I think that this is a safe change, but it's possible that I missed something.
I've done some basic …
=> Implement nested formatting tags

src/main/java/betterquesting/api2/client/gui/panels/content/PanelTextBox.java
Sorry, one more quick tweak that didn't make it in before the other PR was merged 😅
=> Explain semantics of `currUrlStart`, and reset it between tags

src/main/java/betterquesting/api2/client/gui/controls/PanelButtonQuest.java
Fixes https://discord.com/channels/181078474394566657/949447391587733504/1245501878884896939
Instead of dealing with a ton of ternary ops we can just feed it a dummy quest whenever it's null which will hopefully prevent future mishaps completely.
=> Fix crash when creating a new quest

src/main/java/betterquesting/api2/client/gui/GuiScreenCanvas.java
Saves you having to hit the back button a gazillion times while browsing quests or sitting with your finger planted on backspace.
This will only trigger if clicked on empty spaces to keep it from interfering with buttons, on top of that it will also never close the gui, take you to an external gui or return to the BQ home screen when right clicking on the questline gui,
=> Go back to previous screen with right click

src/main/java/betterquesting/api2/client/gui/panels/content/FormattingTag.java
Fix warning tag name: `warning` -> `warn`
`warn` is the original name, which was changed accidentally.
=> Fix warning tag name: `warning` -> `warn`

src/main/java/betterquesting/api/utils/RenderUtils.java, src/main/java/betterquesting/api2/utils/EntityPlayerPreview.java
I decided to do some testing after noticing that the party screen was insanely dark at night and started by commenting out the naga & hydra renders to better focus on the standard rendering. This however turned out to fix the problem entirely. The reason it only affected the party gui is because `EntityList.getEntityString(entity)`  returns null for players.
I also switched it to use the class name which is a less expensive operation than looking up the entity name in a list populated with every registered entity each time it draws.
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15228
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16496
=> Fix party gui rendering & npe

src/main/java/betterquesting/api/api/QuestingAPI.java
previous code used incorrect equality checking for UUIDs.
Fixes various issues with player syncing where this function (QuestingAPI.getPlayer()) is being called.
=> Fix bug that would cause the questing API's getPlayer to be null

src/main/java/betterquesting/client/gui2/GuiQuest.java, src/main/java/betterquesting/questing/QuestInstance.java, src/main/resources/assets/betterquesting/lang/en_US.lang, src/main/resources/assets/betterquesting/lang/ru_RU.lang, src/main/resources/assets/betterquesting/lang/zh_CN.lang
Noticed that for the redstone ore quest in nightlies, its not obvious that this quest uses OR logic for its tasks, and while a note could be added to the description, a way to notify the player that you dont have to do everything would be nice.
latest layout:
TODO
=> Add message about non-AND task logic

src/main/java/bq_standard/client/gui/editors/tasks/GuiEditTaskHunt.java, src/main/java/bq_standard/client/gui/tasks/PanelTaskHunt.java
Some mobs have attributes that cause "unknown attribute" warnings to be spammed on the server even when nbt is ignored.
Example: BG2 attributes when BG2 is replaced with backhand.
=> dont parse hunt task nbt if its ignored

.git-blame-ignore-revs
Makes `git blame` more usable.
Follow-up for #152.
=> Add git blame ignore file

src/main/java/betterquesting/api/questing/rewards/AbstractReward.java, src/main/java/betterquesting/api/storage/BQ_Settings.java, src/main/java/betterquesting/handlers/ConfigHandler.java, src/main/java/bq_standard/rewards/RewardChoice.java, src/main/java/bq_standard/rewards/RewardCommand.java, src/main/java/bq_standard/rewards/RewardItem.java, src/main/java/bq_standard/rewards/RewardQuestCompletion.java, src/main/java/bq_standard/rewards/RewardScoreboard.java, src/main/java/bq_standard/rewards/RewardXP.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18306
This sounds like a easy task, but there are certain rewards that are not meant to be real rewards (such as RewardQuestCompletion), but technical measures to allow more degree of questbook customizability. Disabling these rewards does not always make sense. There are also particular quests that work as a limited crafting bench, e.g. gtnh TF map quest. None of these should be affected by a player toggleable switch.
By default, scoreboard, command and quest completion rewards are marked as ignore no reward. Others are marked as respect no reward settings. Quest authors can override this setting via `ignoreDisabled` setting for each indiviual rewards. This override is supported by every type of reward that comes with …
=> add disable reward mode :Gigachad:

src/main/resources/assets/betterquesting/lang/en_US.lang
This adds some missing localizations for unlocalized names returned by the ItemStack-insensitive version of `Item.getUnlocalizedName()`.
Relevant for the Item/Block stats introduced in https://github.com/GTNewHorizons/Hodgepodge/pull/398.
=> Add Localization

src/main/java/betterquesting/api/utils/NBTConverter.java
Previously they were based off the HashMap key iteration order, which cannot be guaranteed to stay the same across systems and Java versions.
Tested in dev, and it seems to sort the keys alphabetically with no errors in the BQ dev instance.
=> Sort the JSON keys alphabetically before saving to ensure consistent order

src/main/java/betterquesting/client/QuestNotification.java
The item rendering enables depth testing and disables it again after its done. 
This leaks the disabled depth test into normal rendering where its expected to be enabled, because RenderItemStack is used for displaying the quest completion overlay notification, most noticeably causing weird player and tile entity rendering in the inventory.
=> fix depth test GL state leak

src/main/java/betterquesting/client/QuestNotification.java
Currently the quest complete sound (xp jingle noise) plays at 25% volume due to the `PositionedSoundRecord` constructor method used. This is ok for this sound effect, but when adding [new quest sounds](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/19991), they are very quiet due to this reduced volume. This PR makes it that the default quest sound will continue to play at 25% volume, but custom added sounds will play at full volume (still respecting in game volume menu sliders).
=> Make custom quest sounds decent volume

src/main/java/betterquesting/api2/client/gui/resources/textures/OreDictTexture.java, src/main/java/bq_standard/client/gui/rewards/PanelRewardChoice.java, src/main/java/bq_standard/client/gui/rewards/PanelRewardItem.java
This PR aims to fix [this issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20933).
The fix is as outlined in the proposal.
**showCount=false for quest rewards (Consistent with current appearance):**
**Enabling showCount for quest rewards for demonstration:**
- Does not address the issue of all items (as far as I can tell) rendering as oredicttextures, instead of the regular itemtexture.
=> Fix tooltip count not displaying correctly for items
